# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

sudo: false

env:
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19

  - TOX_ENV=py35-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py27-django18

  - TOX_ENV=py35-django17
  - TOX_ENV=py34-django17
  - TOX_ENV=py27-django17

  - TOX_ENV=py35-django16
  - TOX_ENV=py34-django16
  - TOX_ENV=py27-django16

  - TOX_ENV=py35-django15
  - TOX_ENV=py34-django15
  - TOX_ENV=py27-django15

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV
